//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressBookerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class busschedule
    {
        public int scheduleid { get; set; }
        public int busid { get; set; }
        public int routeid { get; set; }
        public System.DateTime departuretime { get; set; }
        public System.DateTime arrivaltime { get; set; }
        public decimal Price { get; set; }

        public virtual bus bus { get; set; }
        public virtual route route { get; set; }
    }
}
