//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressBookerProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class expressbookerEntities : DbContext
    {
        public expressbookerEntities()
            : base("name=expressbookerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<busschedule> busschedules { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
