//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressBookerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedbackid { get; set; }
        public int bookingid { get; set; }
        public int userid { get; set; }
        public string comments { get; set; }
        public int rating { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual user user { get; set; }
    }
}
