//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressBookerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int paymentid { get; set; }
        public int bookingid { get; set; }
        public decimal amount { get; set; }
        public System.DateTime paymentdate { get; set; }
        public string paymentmethod { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
